#!/bin/bash
echo "=== C/C++ Extension Quick Fix ==="
echo ""
echo "The extension is installed at:"
echo "  ~/.vscode/extensions/ms-vscode.cpptools-1.28.3-darwin-arm64"
echo ""
echo "To activate it:"
echo "1. Press Cmd+Shift+X (Extensions)"
echo "2. Search for 'C/C++'"
echo "3. Make sure it's ENABLED (not disabled)"
echo "4. Press Cmd+Shift+P → 'Developer: Reload Window'"
echo ""
echo "After reloading, wait 30 seconds, then:"
echo "5. Press Cmd+Shift+P"
echo "6. Type 'C/C++'"
echo "7. You should see 'C/C++: Reset IntelliSense Database'"
